version: 2
jobs:
  build:
    parallelism: 4
    docker:
      - image: circleci/node:8.9.4
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: sudo yarn global add lerna

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
  test:
    parallelism: 4
    docker:
      - image: circleci/node:8.9.4
      - image: mongo:3.4.5

    steps:
      - checkout
      - run: yarn test
      - run: yarn run style
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
  
    jobs:
      - build
      - test:
          requires:
            - build
